Notify publishing-bot folks about a new branch
As part of the release process, we create an issue, notifying the
publishing-bot folks about the new branch and ask them to update the
bot's configuration.

diff --git a/anago b/anago
--- a/anago
+++ b/anago
@@ -985,6 +985,12 @@ announce () {
   if [[ "$arg" == "--branch" ]]; then
     echo "k8s $RELEASE_BRANCH branch has been created" > $subject_file
     branch_announcement_text > $announcement_file
+
+    # When we create a new branch, we notify the publishing-bot folks by
+    # creating an issue for them
+    gitlib::create_publishing_bot_issue "$RELEASE_BRANCH" || {
+      logecho "$WARNING: Could not create issue for the publishing-bot update"
+    }
   else
     echo "k8s $RELEASE_VERSION_PRIME is live!" > $subject_file
     release_announcement_text > $announcement_file
