[anago] Add better logging for the publishing-bot issue

diff --git a/anago b/anago
--- a/anago
+++ b/anago
@@ -1010,6 +1010,8 @@ announce () {
   local announcement_file="$WORKDIR/announcement.html"
   local subject_file="$WORKDIR/announcement-subject.txt"
   local nomock_flag=""
+  local pubotRc=0
+  local pubotIssue=''
 
   logecho "Creating k8s $RELEASE_VERSION_PRIME announcement in $WORKDIR..."
 
@@ -1019,9 +1021,12 @@ announce () {
 
     # When we create a new branch, we notify the publishing-bot folks by
     # creating an issue for them
-    gitlib::create_publishing_bot_issue "$RELEASE_BRANCH" | gitlib::get_issue_url || {
-      logecho "$WARNING: Could not create issue for the publishing-bot update"
-    }
+    pubotIssue="$( gitlib::create_publishing_bot_issue "$RELEASE_BRANCH" | gitlib::get_issue_url )" || pubotRc=$?
+    if [ "$pubotRc" != '0' ]; then
+      logecho "${WARNING}: Could not create issue for the publishing-bot update"
+    else
+      logecho "${OK}: publishing-bot update issue created: ${pubotIssue}"
+    fi
   else
     echo "k8s $RELEASE_VERSION_PRIME is live!" > $subject_file
     release_announcement_text > $announcement_file
