build(distroless-iptables): add build-time assertion for static nftables
This adds an ldd assertion immediately after staging the nft binary to ensure it doesn't dynamically link against libnftables, libnftnl, or libmnl.

diff --git a/images/build/distroless-iptables/distroless-trixie/Dockerfile b/images/build/distroless-iptables/distroless-trixie/Dockerfile
--- a/images/build/distroless-iptables/distroless-trixie/Dockerfile
+++ b/images/build/distroless-iptables/distroless-trixie/Dockerfile
@@ -21,16 +21,53 @@ COPY stage-binary-and-deps.sh /
 COPY stage-binaries-from-package.sh /
 COPY package-utils.sh /
 
+# 1. Install compilation toolchain and dependencies
+RUN apt-get -y update && \
+    apt-get -y dist-upgrade && \
+    apt-get -y install --no-install-recommends \
+        git ca-certificates build-essential autoconf automake libtool \
+        bison flex pkg-config libgmp-dev libreadline-dev \
+        libedit-dev libjansson-dev
+
+# 2. Build libmnl
+ARG LIBMNL_VERSION="libmnl-1.0.5"
+ARG LIBMNL_CLONE_URL="https://git.netfilter.org/libmnl"
+RUN git clone --filter=tree:0 "${LIBMNL_CLONE_URL}" /libmnl && \
+    cd /libmnl && \
+    git checkout "${LIBMNL_VERSION}" && \
+    ./autogen.sh && ./configure --enable-static --disable-shared && make && make install
+
+# 3. Build libnftnl
+ARG LIBNFTNL_VERSION="libnftnl-1.2.9"
+ARG LIBNFTNL_CLONE_URL="https://git.netfilter.org/libnftnl"
+RUN git clone --filter=tree:0 "${LIBNFTNL_CLONE_URL}" /libnftnl && \
+    cd /libnftnl && \
+    git checkout "${LIBNFTNL_VERSION}" && \
+    ./autogen.sh && ./configure --enable-static --disable-shared && make && make install
+
+# 4. Build nftables
+ARG NFTABLES_VERSION="v1.1.3"
+ARG NFTABLES_CLONE_URL="https://git.netfilter.org/nftables"
+COPY patches /patches
+RUN git clone --filter=tree:0 "${NFTABLES_CLONE_URL}" /nftables && \
+    cd /nftables && \
+    git checkout "${NFTABLES_VERSION}" && \
+    for p in $(cat /patches/series); do patch -p1 --forward < "/patches/$p" || true; done && \
+    ./autogen.sh && \
+    ./configure --disable-python --disable-man-doc --sbindir=/usr/sbin --enable-static --disable-shared && \
+    make && make install
+
+RUN ldconfig
+
 # TODO: /bin/sleep is used by a specific e2e test
 ARG STAGE_DIR="/opt/stage"
-RUN apt -y update && \
-    apt -y dist-upgrade && \
-    apt -y install bash curl && \
+RUN apt-get -y install bash curl && \
     mkdir -p "${STAGE_DIR}" && \
     /stage-binaries-from-package.sh "${STAGE_DIR}" ipset \
     iptables    \
-    nftables    \
     kmod        && \
+    /stage-binary-and-deps.sh "${STAGE_DIR}" /usr/sbin/nft && \
+    if ldd "${STAGE_DIR}/usr/sbin/nft" | grep -qE '(libnftables|libnftnl|libmnl)'; then echo "Error: nft is dynamically linked to netfilter libraries" && exit 1; fi && \
     `# below binaries and dash are used by iptables-wrapper-installer.sh` \
     /stage-binary-and-deps.sh "${STAGE_DIR}" /bin/dash \
     /bin/cat \
